# Generated by Django 2.0.5 on 2018-07-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(default='aaa@bb.c', max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default='21-07-2018', verbose_name='signup date')),
            ],
        ),
    ]
