# Generated by Django 2.0.5 on 2018-07-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='date',
        ),
    ]
