# Generated by Django 2.0.5 on 2018-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_contact_us_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.IntegerField(default=10),
        ),
    ]
