# Generated by Django 2.0.5 on 2018-07-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180721_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
