# Generated by Django 2.0.5 on 2018-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20180721_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(default='xxxxxxxxxx', max_length=70),
        ),
    ]
